sudo: required
dist: trusty

language: node_js

node_js:
  - 6.10.1

install:
  - npm install --global @angular/cli
  - npm install --global gulp

before_script:
  - npm install

script:
  - npm run server:test
  - ng lint
  - ng test --browsers=PhantomJS --progress=false --code-coverage --single-run
